<select id = "school"> 
              <option selected>What Institution?</option>
              <option class = "option">Federal University of Technology, Minna</option>
              <option class = "option">Federal University of Technology, Owerri</option>
              <option class = "option">ABU Zaria</option>
              <option class = "option">Abia State University, Abia</option>
              <option class = "option">Bida Polytechnic, Bida</option>
</select>